import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Side } from "@/components/Side";
import { DarkProvider } from "@/context/theme/DarkProvider";
import clsx from "clsx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // grid grid-cols-1 md:grid-cols-[16rem_1fr]
    <html lang="en" suppressHydrationWarning>
      <head></head>
      <body
        className={clsx(
          geistSans.variable,
          geistMono.variable,
          "antialiased",
          "grid grid-cols-1 md:grid-cols-[16rem_1fr] max-w-6xl mx-auto"
        )}
      >
        <script
          dangerouslySetInnerHTML={{
            __html: `
      (function() {
        const stored = localStorage.getItem('theme');
        const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
        const theme = stored || (prefersDark ? 'dark' : 'light');
        document.documentElement.classList.remove('light','dark');
        document.documentElement.classList.add(theme);
      })();
    `,
          }}
        />
        <DarkProvider>
          <Side className="top-0 md:sticky md:self-start" />
          <div className={clsx("min-h-screen", "p-4 lg:p-20 md:p-10")}>{children}</div>
        </DarkProvider>
      </body>
    </html>
  );
}
